
package:
    name: dioptas
    version: 0.4.5.gsecars

source:
    git_url: https://github.com/erangre/Dioptas
    git_tag: dioptas_gsecars

build:
  number: 1
  script: python setup.py install

requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy
        - pyqt
        - pyqtgraph
        - python.app # [osx]
        - libgfortran # [linux64 or osx]
        - patchelf # [linux]
        - lmfit
        - fabio # [linux64 or osx]
        - pyfai # [linux64 or osx]
        - pycifrw
        - future
        - scikit-image
        - qtpy
        - pyshortcuts
        - cython
        - vs2015_runtime

    run:
        - python
        - setuptools
        - numpy
        - scipy
        - pyqt
        - pyqtgraph
        - python.app # [osx]
        - lmfit
        - fabio # [linux64 or osx]
        - pyfai # [linux64 or osx]
        - pycifrw
        - future
        - scikit-image
        - qtpy
        - pyshortcuts
        - cython
        - vs2015_runtime

test:
    imports:
        - dioptas

about:
    home: https://github.com/Dioptas/Dioptas
    license: GPL3
    summary: GUI program for reduction and exploration of 2D X-ray diffraction data
